### PR TITLE
[feat] remove prefix v of engine version

### PR DESCRIPTION
**Pull request by lenoxzhao**
Remove prefix v of engine version from deploy-quick.md of v1.3.2 and v1.4.0.
移除了v1.3.2和v1.4.0单机部署文档中引擎版本名的前缀v。

Related issues: https://github.com/apache/linkis/issues/4669

### CODE REVIEW

**Comment by aiceflower** [comment]
Global search and modify
image

**Comment by lenoxzhao** [comment]
> Global search and modify image

Thanks, I will do it later.

**Comment by lenoxzhao** [comment]
Done.I only modify those files of v1.3.2 and v1.4.0 because I find the engine version name still starts with prefix v below v1.3.2. @aiceflower

**Comment by casionone** [comment]
> Done.I only modify those files of v1.3.2 and v1.4.0 because I find the engine version name still starts with prefix v below v1.3.2. @aiceflower

Yes

**Comment by aiceflower** [comment]
LGTM.

**Pull request merged**
