### PR TITLE
[feat] remove incubating

### PR DESCRIPTION
**Pull request by lenoxzhao**
Remove "incubating" from deploy-quick.md of v1.3.1, v1.3.2 and v1.4.0 based on installation package of v1.3.1.
根据v1.3.1安装包，移除了v1.3.1、v1.3.2和v1.4.0单机部署文档中的incubating词。

Related issues: https://github.com/apache/linkis/issues/4668

### CODE REVIEW

**Comment by aiceflower** [comment]
You can search globally for places that contain incubating. 
image

**Comment by lenoxzhao** [comment]
> You can search globally for places that contain incubating. image

Thanks, I will do it later.

**Comment by lenoxzhao** [comment]
Done.
The software installation package name was changed starting from v1.3.1, so I only modified the relevant files for v1.3.1, v1.3.2, and v1.4.0. @aiceflower

**Comment by aiceflower** [comment]
LGTM.

**Pull request merged**
