### PR TITLE
[BUG] fix wrong ip command in deploy-console.md and web-install.md

### LINKED ISSUE #606: [BUG] fix wrong ip command in deploy-console.md and web-install.md
actuall ip parsing  command is invalid for the lack of `space`
we need to fix wrong ip command in deploy-console.md and web-install.md to avoid misunderstanding.

### PR DESCRIPTION
**Pull request by GuoPhilipse**
fix #606

### CODE REVIEW

**Comment by casionone** [comment]
https://github.com/apache/incubator-linkis/pull/1989 
There are problems with multi network ip, consistent with the actual code?

**Comment by GuoPhilipse** [comment]
> [apache/incubator-linkis#1989](https://github.com/apache/incubator-linkis/pull/1989) There are problems with multi network ip, consistent with the actual code?

Yes, I just have done a simple test, it will actually get two ip address ,not as expected.

I think maybe  we should only set the `linkis_ipaddr` as  127.0.0.1 , the user can change to there real ip if necessary.
how do you think?

#####test cases#####
`
[hdfs@hadoop-036-011 ~]$ echo $(ip addr | awk '/^[0-9]+: / {}; /inet.*global/ {print gensub(/(.*)\/(.*)/, "\\1" , "g", $2)}')
`
result will be `172.22.36.11 172.17.0.1`
#####test cases#####

**Comment by casionone** [comment]
> yes, only set 127.0.0.1 as example, user can change to there real ip if necessary

**Review by casionone — APPROVED** [review]

**Comment by casionone** [comment]
LGTM

**Pull request merged**
