### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by legendtkl**

### CODE REVIEW

**Comment by legendtkl** [comment]
Hi, @peacewong , would you help review this?

Thanks, kelu.

**Comment by casionone** [comment]
> Hi, @peacewong , would you help review this?
> 
> Thanks, kelu.

I think it's better to submit to the dev branch

**Comment by legendtkl** [comment]
Thanks for the reply, @casionone . I will do it later.

Thanks, kelu.

**Comment by legendtkl** [comment]
Hi, @casionone , I open another pr for this. ref: https://github.com/apache/incubator-linkis-website/pull/71

Let's close this.

**Pull request closed without merging**
