### PR TITLE
feat: add entry link of data source

### PR DESCRIPTION
**Pull request by CoderSerio**
add entry link to data source supported

image

fix issue #4671 of linkis(https://github.com/apache/linkis/issues/4671)

### CODE REVIEW

**Comment by aiceflower** [comment]
The corresponding English documents also need to be modified.
clickhouse is not listed.

**Comment by CoderSerio** [comment]
> The corresponding English documents also need to be modified. clickhouse is not listed.

Get. 
I' ll make adjustment tonight.

**Comment by casionone** [comment]
Capitalize the first letter of the table header

**Comment by CoderSerio** [comment]
English Docs and table headers have also been modified.

But the feat  of adding the data source list item, like `clickhouse`, is ignored in this time, because I noticed that it's related to issue 4670 of linkis (https://github.com/apache/linkis/issues/4670).

Another contributor, @zhaowenkai111 hoped to implement this.

**Comment by aiceflower** [comment]
It is recommended to add another section listing supported data sources.
You can display data sources and link information in a table. The supported data sources are as follows.
image

**Comment by CoderSerio** [comment]
Done.
I have replaced it with a table:
image

**Comment by casionone** [comment]
Only update the two most recent versions, 1.4.0 and 1.3.2

**Comment by CoderSerio** [comment]
> Only update the two most recent versions, 1.4.0 and 1.3.2

Done

**Pull request merged**
