### PR TITLE
[CSS] Improving Website Appearance and User Experience

### PR DESCRIPTION
**Pull request by Shriansh2002**
This pull request includes two changes to improve the website's appearance and user experience.

-   **[CSS] Updated Hero Section**

    I have made significant updates to the CSS code for the hero section. By implementing new styles and layouts, the hero section now delivers a more captivating and engaging experience to visitors. The changes include refined typography, improved spacing, and a visually appealing background image that aligns with the website's theme.

    **Screenshots:**

    | Before                                                                                                         | After                                                                                                         |
    | -------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
    | Before Image | After Image |

    <br />

-   **[CSS] Remove Icon from website footer list**
    I have removed the icons associated with each item in the website footer list using CSS. This adjustment creates a cleaner and more streamlined appearance, allowing the focus to be on the essential information within the footer. By removing the icons, the footer now maintains a consistent and cohesive design throughout the website.

    | Before                                                                                                         | After                                                                                                         |
    | -------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
    | Before Image | After Image |

### CODE REVIEW

**Comment by Shriansh2002** [comment]
ReUpdated the Footer Link

Screenshot 2023-06-20 at 5 43 22 PM

**Comment by casionone** [comment]
LGTM

**Comment by Shriansh2002** [comment]
If you liked the UI, please Review and Merge it into the `dev` branch.

**Review by CoderSerio — COMMENTED** [review]
LGTM

**Comment by aiceflower** [comment]
LGTM.

**Comment by Shriansh2002** [comment]
The Main site is not yet updated

**Pull request merged**
